#!/usr/bin/perl

use strict;
use warnings;

use HTML::StripScripts::Parser qw( );
use HTML::Tidy qw( );

my $strip = HTML::StripScripts::Parser->new(
  { "AllowHref" => 1
  , "AllowSrc"  => 1
  , "Context"   => "Flow"
  } );

my $tidy = HTML::Tidy->new(
  { "add-xml-decl"                => 0
  , "add-xml-space"               => 0
  , "assume-xml-procins"          => 1
  , "bare"                        => 1
  , "clean"                       => 1
  , "doctype"                     => "omit"
  , "drop-proprietary-attributes" => 1
  , "enclose-block-text"          => 1
  , "enclose-text"                => 1
  , "hide-comments"               => 1
  , "numeric-entities"            => 1
  , "output-xhtml"                => 1
  , "show-body-only"              => 1
  , "show-errors"                 => 0
  , "show-warnings"               => 0
  , "tidy-mark"                   => 0
  } );

foreach my $file ( @ARGV ) {

  open( FILE, "<", $file ) or die "Couldn't open $file: $!";

  my $html;

  {
    local $/;
    $html = <FILE>;
  };

  close( FILE );

  print $strip->filter_html( $tidy->clean( $html ) );

};
